name: Dockerimage Main

on:
  schedule:
    - cron: '29 21 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tdarr-dovi-hdr10plus:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Fetch version tags
        id: fetch_tags
        run: |
          DOVI_TOOL_TAG=$(curl -s https://api.github.com/repos/quietvoid/dovi_tool/releases/latest | grep -oP '(?<="tag_name": ")[^"]*')
          HDR10PLUS_TOOL_TAG=$(curl -s https://api.github.com/repos/quietvoid/hdr10plus_tool/releases/latest | grep -oP '(?<="tag_name": ")[^"]*')
          MP4BOX_TAG=$(curl -s https://api.github.com/repos/gpac/gpac/tags | grep -oP -m 1 '(?<="name": ")[^"]*')

          echo "DOVI_TOOL_TAG=${DOVI_TOOL_TAG}" >> $GITHUB_ENV
          echo "HDR10PLUS_TOOL_TAG=${HDR10PLUS_TOOL_TAG}" >> $GITHUB_ENV
          echo "MP4BOX_TAG=${MP4BOX_TAG}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: dungfu/tdarr-dovi-hdr10plus:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
